### ISSUE TITLE
Cloud graphics

### ISSUE THREAD

**Issue by sebastiandoe5** [waterdapp/waterdapp.github.io#11]
also do animation

**Comment by altubby** [comment]
![image](https://user-images.githubusercontent.com/53750687/62475403-e23de880-b79c-11e9-9b7d-95939117763c.png)

**Comment by altubby** [comment]
![image](https://user-images.githubusercontent.com/53750687/62475911-ee767580-b79d-11e9-9333-14b65f3469a4.png)

**Comment by altubby** [comment]
![image](https://user-images.githubusercontent.com/53750687/62526489-427e6a00-b831-11e9-974d-b73e075e53ce.png)

**Comment by sebastiandoe5** [comment]
This issue will now be #27, I have closed this issue.
