### ISSUE TITLE
Things to design

### ISSUE THREAD

**Issue by sebastiandoe5** [waterdapp/waterdapp.github.io#18]
Please comment below when these designs are completed and I'll check them off the list.

- [x] Logo (Natasha)
- [x] Clouds (Alice)
- [x] Pot
- [x] Watering Can
- [x] Hydration and Health bars
- [x] Floating Island for the plant
- [x] Sun
- [x] Moon
- [x] Seeds (Earl)
- [x] Water
- [x] Flowers
- [x] Speed Bar (Seb)

**Comment by altubby** [comment]
![image](https://user-images.githubusercontent.com/53750687/62529574-d0a91f00-b836-11e9-8796-93d9f94218c1.png)

**Comment by altubby** [comment]
![image](https://user-images.githubusercontent.com/53750687/62532219-d3f2d980-b83b-11e9-8664-2aa74bfc35f5.png)

**Comment by altubby** [comment]
![image](https://user-images.githubusercontent.com/53750687/62538620-2687c200-b84b-11e9-867a-af79db911494.png)

**Comment by altubby** [comment]
![image](https://user-images.githubusercontent.com/53750687/62542953-c5fd8280-b854-11e9-98ad-7b1ac79f765b.png)

**Comment by altubby** [comment]
![image](https://user-images.githubusercontent.com/53750687/62543321-9ef38080-b855-11e9-9363-406318f95b5c.png)

**Comment by altubby** [comment]
![image](https://user-images.githubusercontent.com/53750687/62544291-6654a680-b857-11e9-8f7d-ddb6d99253ed.png)

**Comment by altubby** [comment]
![image](https://user-images.githubusercontent.com/53750687/62548370-99e6ff00-b85e-11e9-9aaa-b8a341f82155.png)

**Comment by altubby** [comment]
![image](https://user-images.githubusercontent.com/53750687/62548410-a703ee00-b85e-11e9-9774-91bc57e71355.png)

**Comment by altubby** [comment]
![image](https://user-images.githubusercontent.com/53750687/62549843-18dd3700-b861-11e9-8e3c-cac16b82118e.png)

**Comment by altubby** [comment]
![image](https://user-images.githubusercontent.com/53750687/62550453-31018600-b862-11e9-82fa-358a6076f67c.png)

**Comment by altubby** [comment]
![image](https://user-images.githubusercontent.com/53750687/62551563-247e2d00-b864-11e9-9d3f-cc78b582ab7b.png)

**Comment by sebastiandoe5** [comment]
Finished, issue now closed.
