### ISSUE TITLE
Pests affect plant

### ISSUE THREAD

**Issue by sebastiandoe5** [waterdapp/waterdapp.github.io#29]
Affects 50% of health, right click to use pesticide.

**Comment by altubby** [comment]
![image](https://user-images.githubusercontent.com/53750687/62614909-36afa800-b904-11e9-97cc-a9a6b67c6a08.png)

**Comment by altubby** [comment]
![image](https://user-images.githubusercontent.com/53750687/62616099-a4f56a00-b906-11e9-803d-2010b67f1196.png)

**Comment by altubby** [comment]
![image](https://user-images.githubusercontent.com/53750687/62622810-3371e780-b917-11e9-8f9e-62593c431d8d.png)

**Comment by altubby** [comment]
![image](https://user-images.githubusercontent.com/53750687/62623188-2ef9fe80-b918-11e9-9452-931e2a21991a.png)

**Comment by altubby** [comment]
still need to wrok out how to KILLLL the bug

**Comment by altubby** [comment]
colision

**Comment by altubby** [comment]
collision

**Comment by altubby** [comment]
bug decreases health,click to kill, randomly appears

**Comment by altubby** [comment]
![image](https://user-images.githubusercontent.com/53750687/62773514-3c3ef680-ba9a-11e9-8251-0657976b1ea2.png)
