### ISSUE TITLE
Waterfall 

### ISSUE THREAD

**Issue by sebastiandoe5** [waterdapp/waterdapp.github.io#44]

**Comment by WaterdPlantNua** [comment]
I might do this too

**Comment by WaterdPlantNua** [comment]
one quarter done

**Comment by altubby** [comment]
![image](https://user-images.githubusercontent.com/53750687/62710887-09d8bf00-b9f0-11e9-8c5f-234b032230cc.png)

**Comment by altubby** [comment]
waterfall done
