### ISSUE TITLE
Seeds & Fruit Classes

### ISSUE THREAD

**Issue by gamirou** [waterdapp/waterdapp.github.io#50]
It will make the code more organised and easier to use when I am going to implement the money  system.

**Comment by gamirou** [comment]
@WaterdPlantNua Could you commit once you finish the descriptions?

**Comment by WaterdPlantNua** [comment]
function seedDataBody() {
  let message2 = '';
  let infoLabel = createP('seedDataBody');
  infoLabel.parent('sketchHolder');
  infoLabel.id('seedDataBody');
  let message = '';
  if (randNum == 1) {
    message = 'you have found a generic seed!';
    message2 = "these are dirt cheap and [enter generic fact here]"
  } else if (randNum == 2) {
    message = 'you have found a pearl seed!';
    message2 = "The pearl seed is a famous trickster plant, <br>because despite the name, pearl seeds are worth<br> very little.Howerer, they do have a pleasant<br>aroma when crushed."
  } else if (randNum == 3) {
    message = 'you have found a pear seed!';
    message2 = "The pear seed is misleadingly named, as the tree <br>doesn't actually grow pears. Instead, the fruits <br>of the pear tree are actually bitter,<br> pear shaped pods which are used in many medicianal remedys."
  } else if (randNum == 4) {
    message = 'you have found a ginger seed!';
    message = "If you enjoy the taste of ginger, then a ginger tree<br>will be an exellent addition to your garden! The fruits<br> of the tree are the famous root (don't ask),<br> so you get a year long supply if you look after your plant!"
  } else if (randNum == 5) {
    message = 'you have found a coal seed!';
    message2 = "When the coal tree and it's seeds were found, it brought <br> the end of destructive coal mining, as every part of<br> the tree burns like coal, and farming the species is <br> much easier than mining."
  } else if (randNum == 6) {
    message = 'you have found a pebble seed!';
    message2 = "although abundant, pebble seeds can be quite hard <br>to find,as they blend into their most common habitat, <br>shingle beaches.The wood of the pebble tree becomes as<br> hard as stone when left in seawater for five days."
  } else if (randNum == 7) {
    message = 'you have found a blood seed!';
    message2 = "The blood seed is widely regarded as Mother Nature's <br>most accursed creation, and folk tales tell of blood<br> trees using their branches to skewer unwary travellers."
  } else if (randNum == 8) {
    message = 'you have found a potato seed!'
    message2 = "Did you know that the potato seed can be eaten,<br> and is rumored to have a plain, bland flavour?"
  }
  infoLabel.html(`
    <p>
    ${message}
    </p>
    <img width="50px" src=${'../src/assets/seeds/seed'.concat(randNum, '.png')}></img>
    <p>
    ${message2}
    </p>
  `)
}
#seedDataTitle{
    font-family: 'Press Start 2P', cursive;
    position: absolute;
    color: white;
    top: 50px;
    font-size: 15px;
    right: 75px;
}
#seedDataBody{
    font-family: 'Press Start 2P', cursive;
    position: absolute;
    color: white;
    top: 70px;
    font-size: 15px;
    right: 75px;

}
#seedDataFunFact{
    font-family: 'Press Start 2P', cursive;
    position: absolute;
    color: white;
    top: 90px;
    font-size: 15px;
    right: 75px;

}

**Comment by gamirou** [comment]
- [x] Seeds
- [ ] Fruits
